/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.Address;
import model.Doctor;
import model.Driver;
import model.InsuranceCoverage;
import model.Paitent;
import model.Person;
import model.VehicleRegisteration;

/**
 *
 * @author Shreya Bage
 */
public class DisplayJPanel extends javax.swing.JFrame {

    /**
     * Creates new form DisplayJPanel
     */
    Address address;
    Doctor doctor;
    Driver driver;
    InsuranceCoverage insuranceCoverage;
    Paitent paitent;
    Person person;
    VehicleRegisteration vehicleRegisteration;
    
    
    public DisplayJPanel() {
        initComponents();
        
        
    address = new Address();
    doctor = new doctor();
    driver = new Driver();
    insuranceCoverage = new InsuranceCoverage();
    paitent = new Paitent();
    person = new Person();
    vehicleRegisteration = new VehicleRegisteration();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        driverbut = new javax.swing.JButton();
        insbut = new javax.swing.JButton();
        docbut = new javax.swing.JButton();
        addressbut = new javax.swing.JButton();
        paitbut = new javax.swing.JButton();
        persbut = new javax.swing.JButton();
        vehiclebut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        driverbut.setText("Driver");

        insbut.setText("Insurance");

        docbut.setText("Doctor");
        docbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docbutActionPerformed(evt);
            }
        });

        addressbut.setText("Address");
        addressbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressbutActionPerformed(evt);
            }
        });

        paitbut.setText("Paitent");
        paitbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paitbutActionPerformed(evt);
            }
        });

        persbut.setText("Person");
        persbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persbutActionPerformed(evt);
            }
        });

        vehiclebut.setText("Vehicle");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(insbut, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docbut, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paitbut, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressbut, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(persbut, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(196, 196, 196))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(driverbut, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(vehiclebut, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insbut)
                    .addComponent(addressbut))
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(persbut)
                    .addComponent(docbut))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paitbut)
                    .addComponent(driverbut))
                .addGap(34, 34, 34)
                .addComponent(vehiclebut)
                .addGap(0, 91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paitbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paitbutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paitbutActionPerformed

    private void addressbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressbutActionPerformed
        AddressJPanel addressPanel = new AddressJPanel(address);

    }//GEN-LAST:event_addressbutActionPerformed

    private void docbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docbutActionPerformed
        DoctorJPanel doctorPanel = new DoctorJPanel(doctor);
    }//GEN-LAST:event_docbutActionPerformed

    private void persbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persbutActionPerformed
        PersonJPanel personPanel = new PersonJPanel(person);
    }//GEN-LAST:event_persbutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayJPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addressbut;
    private javax.swing.JButton docbut;
    private javax.swing.JButton driverbut;
    private javax.swing.JButton insbut;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton paitbut;
    private javax.swing.JButton persbut;
    private javax.swing.JButton vehiclebut;
    // End of variables declaration//GEN-END:variables
}
