/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author Shreya Bage
 */
public class PaitentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaitentJPanel
     */
    public PaitentJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ic = new javax.swing.JLabel();
        paitentid_text = new javax.swing.JTextField();
        primarydoctor_text = new javax.swing.JTextField();
        lastvisit_text = new javax.swing.JTextField();
        na_text = new javax.swing.JTextField();
        allergies_text = new javax.swing.JTextField();
        meds_text = new javax.swing.JTextField();
        lastvisit = new javax.swing.JLabel();
        ic_text = new javax.swing.JTextField();
        na = new javax.swing.JLabel();
        allergies = new javax.swing.JLabel();
        meds = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        paitentid = new javax.swing.JLabel();
        primarydoctor = new javax.swing.JLabel();
        paitbut1 = new javax.swing.JButton();

        ic.setText("insuranceCoverage");

        paitentid_text.setText("jTextField1");
        paitentid_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paitentid_textActionPerformed(evt);
            }
        });

        primarydoctor_text.setText("jTextField2");

        lastvisit_text.setText("jTextField3");

        na_text.setText("jTextField4");

        allergies_text.setText("jTextField5");

        meds_text.setText("jTextField6");

        lastvisit.setText("lastvisit");

        ic_text.setText("jTextField7");

        na.setText("nextappoitment");

        allergies.setText("allergies");

        meds.setText("onMedication");

        jLabel1.setText("Paitent");

        paitentid.setText("paitentid");

        primarydoctor.setText("primarydoctor");

        paitbut1.setText("Paitent");
        paitbut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paitbut1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(primarydoctor)
                            .addComponent(paitentid)
                            .addComponent(lastvisit)
                            .addComponent(na)
                            .addComponent(allergies)
                            .addComponent(meds)
                            .addComponent(ic))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paitbut1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paitentid_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(primarydoctor_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastvisit_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(na_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(allergies_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(meds_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(ic_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paitentid)
                    .addComponent(paitentid_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(primarydoctor)
                    .addComponent(primarydoctor_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastvisit)
                    .addComponent(lastvisit_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(na)
                    .addComponent(na_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allergies)
                    .addComponent(allergies_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meds)
                    .addComponent(meds_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ic)
                    .addComponent(ic_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(paitbut1)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void paitentid_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paitentid_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paitentid_textActionPerformed

    private void paitbut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paitbut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paitbut1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allergies;
    private javax.swing.JTextField allergies_text;
    private javax.swing.JLabel ic;
    private javax.swing.JTextField ic_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastvisit;
    private javax.swing.JTextField lastvisit_text;
    private javax.swing.JLabel meds;
    private javax.swing.JTextField meds_text;
    private javax.swing.JLabel na;
    private javax.swing.JTextField na_text;
    private javax.swing.JButton paitbut1;
    private javax.swing.JLabel paitentid;
    private javax.swing.JTextField paitentid_text;
    private javax.swing.JLabel primarydoctor;
    private javax.swing.JTextField primarydoctor_text;
    // End of variables declaration//GEN-END:variables
}
